# Generated by Django 2.0 on 2018-12-28 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pro_dateils_jihua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=30, verbose_name='项目阶段名称')),
                ('pro_start_time', models.DateField(verbose_name='项目阶段开始时间')),
                ('pro_stop_time', models.DateField(verbose_name='项目阶段完成时间')),
                ('pro_desc', models.CharField(max_length=100, verbose_name='项目阶段描述')),
            ],
            options={
                'verbose_name': '项目详情-计划',
                'verbose_name_plural': '项目详情-计划',
                'db_table': 'pro_dateils_jihua',
            },
        ),
        migrations.CreateModel(
            name='Pro_dateils_shiji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=30, verbose_name='项目阶段名称')),
                ('pro_start_time', models.DateField(verbose_name='项目阶段开始时间')),
                ('pro_stop_time', models.DateField(verbose_name='项目阶段完成时间')),
                ('pro_desc', models.CharField(max_length=100, verbose_name='项目阶段描述')),
            ],
            options={
                'verbose_name': '项目详情-实际',
                'verbose_name_plural': '项目详情-实际',
                'db_table': 'pro_dateils_shiji',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_num', models.CharField(max_length=10, verbose_name='项目编号')),
                ('p_name', models.CharField(max_length=20, verbose_name='项目名称')),
                ('p_start_time', models.DateField()),
                ('p_stop_time', models.DateField(null=True)),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Project_dateils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(0, '计划'), (1, '实际')], default=0)),
                ('analysis', models.CharField(max_length=20)),
                ('design', models.CharField(max_length=20)),
                ('realize', models.CharField(max_length=20)),
                ('SIT_jd', models.CharField(max_length=20)),
                ('UAT_jd', models.CharField(max_length=20)),
                ('verify', models.CharField(max_length=20)),
                ('online', models.CharField(max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.Project')),
            ],
            options={
                'verbose_name': '项目详情',
                'verbose_name_plural': '项目详情',
                'db_table': 'project_dateils',
            },
        ),
    ]
