# Generated by Django 2.0 on 2018-12-28 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='p_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='项目负责人'),
        ),
        migrations.AddField(
            model_name='pro_dateils_shiji',
            name='project_sj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.Project', verbose_name='项目实际进展'),
        ),
        migrations.AddField(
            model_name='pro_dateils_jihua',
            name='project_jh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.Project', verbose_name='项目计划'),
        ),
    ]
