# Generated by Django 2.0 on 2018-12-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_auto_20181228_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_dateils_shiji',
            name='pro_start_time_jh',
            field=models.DateField(null=True, verbose_name='项目阶段开始时间'),
        ),
        migrations.AddField(
            model_name='pro_dateils_shiji',
            name='pro_stop_time_jh',
            field=models.DateField(null=True, verbose_name='项目阶段开始时间'),
        ),
    ]
