# Generated by Django 2.0 on 2018-12-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opeartion_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=50, verbose_name='操作详情')),
                ('operate_time', models.DateTimeField()),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('remark', models.CharField(max_length=100, verbose_name='备注')),
                ('hostname', models.CharField(max_length=20, null=True, verbose_name='主机名称')),
                ('ip', models.CharField(max_length=20, null=True, verbose_name='ip地址')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_log',
            },
        ),
    ]
